Repository EUCweb/BIS-F, pull requests merged in 2022-11, with the labels that each got.

#331 Fix for MS_AAD_HybribLeave
  ADMX/BaseImageScriptFramework.admx
  ADMX/en-US/BaseImageScriptFramework.adml
  Framework/SubCall/Preparation/97_PrepBISF_PRE_BaseImage.ps1
Labels: Priority: High, Merge Issue

#346 Update bug report, feature request and add a question form
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: Merge Issue

#353 Update 10_PrepBISF_AV-WinDefend.ps1
  Framework/SubCall/Preparation/10_PrepBISF_AV-WinDefend.ps1
Labels: Priority: Medium, Merge Issue

#348 Add Symantec to VIE search folders
  Framework/SubCall/Preparation/10_PrepBISF_AV-SEP.ps1
Labels: Priority: Medium, Merge Issue

#345 Fixes RES One AM agent from not being registered
  Framework/SubCall/Preparation/10_PrepBISF_RES.ps1
Labels: Priority: Medium, Merge Issue
